jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: *
buid:
  needs: setup
  runs-on: ubuntu-latest
  steps:
    - run: **
test:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - run: ***
